### ISSUE TITLE
Explain the overview page

### ISSUE THREAD

**Issue by cryptax** [FrenchYeti/dexcalibur-doc#13]
The overview page of Dexcalibur is nice, and we see the different namespaces, but besides that are there other usages to this screen that I am missing? It's not clear what we should/can do with this to me...

![overview](https://user-images.githubusercontent.com/2493690/101886600-0503bc80-3b9c-11eb-8054-d2f4fe23149f.png)

**Comment by FrenchYeti** [comment]
Since Dexcalibur v0.7.0, this feature is partially broken because packages cannot be explored. Previous versions allow users to browse package and it updates content of the grid under the map with package details.

Effectively, there are multiple ways to interpret this treemap.
 - Treemap shows classes distribution over app + android API of the target device
 - It is a quick way to view proguard rules/static obfuscation   affecting packages/classes name, and third-part component
 - Size of the square depends of its absolute size ( number of nested classes)
 - If the name of a square contains a dot ` . `, it means the package has only a single package so name of packages have been concated 
 - If the name of a square is `[root]`, that means there are classes  at root. Such classes are not contained into a package.

Into your screenshot, 'd' package is very huge compared to others. So, it probably contains the main part of the app. But if you search security functions, crypto func, functions gathering device data (and so) from third-part library, it can be into a small square with opaque name.
